GET http://localhost:3000/users

###

GET http://localhost:3000/users/14

###

POST http://localhost:3000/users 
Content-Type: appllication/json

{
    "name": "rahul yadav",
    "age": "21",
    "email": "rahulyadav3766@gmail.com"
}